name: "Build"

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: false
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact"
        value: ${{ jobs.main.outputs.artifact-name }}
      artifact-id:
        description: "ID of the uploaded artifact"
        value: ${{ jobs.main.outputs.artifact-id }}
      artifact-url:
        description: "URL of the uploaded artifact"
        value: ${{ jobs.main.outputs.artifact-url }}

env:
  # https://github.com/actions/runner-images/issues/70
  NODE_OPTIONS: "--max_old_space_size=4096"

permissions: {}

jobs:
  echo-inputs:
    name: "Echo Inputs"
    runs-on: ubuntu-latest
    steps:
      - id: echo
        name: "Echo Inputs"
        run: |
          echo "verbose=${{ github.event.inputs.verbose }}"
  about:
    name: "About"
    uses: "./.github/workflows/about.yml"
  main:
    name: "Main"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - about
    env:
      name: ${{ needs.about.outputs.name }}
      nodeVersion: ${{ needs.about.outputs.nodeVersion }}
      pnpmVersion: ${{ needs.about.outputs.pnpmVersion }}
      version: ${{ needs.about.outputs.version }}
    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.result }}
      artifact-id: ${{ steps.upload-child-theme.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-child-theme.outputs.artifact-url }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: installPnpm
        name: "Install: Use PNPM ${{ env.pnpmVersion }}"
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpmVersion }}
          run_install: false
      - id: installNodeJs
        name: "Install: Use Node.js ${{ env.nodeVersion }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: "pnpm"
      - id: install
        name: Install
        run: |
          pnpm install --frozen-lockfile
      - id: build
        name: "Build"
        run: |
          pnpm -r build
      - id: artifact-name
        name: "Generate Artifact Name"
        run: |
          result="${{ env.name }}-v${{ env.version }}"
          echo "result=${result}" >> $GITHUB_OUTPUT
      - id: upload-child-theme
        name: "Upload Child Theme"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.result }}
          path: build/**/*
          retention-days: 10
          compression-level: 9
      - id: output-build-info
        name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.upload-child-theme.outputs.artifact-id }}'
  verbose:
    name: "Verbose"
    runs-on: ubuntu-latest
    needs:
      - main
    if: ${{ github.event.inputs.verbose }}
    steps:
      - id: output
        name: "Output"
        run: |
          echo "# Build Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Child Theme: [${{ needs.main.outputs.artifact-name }}.zip](${{ needs.main.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY
