name: "Lint (Util)"

# Runs linters for this project.

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: false

env:
  # https://github.com/actions/runner-images/issues/70
  NODE_OPTIONS: "--max_old_space_size=4096"

permissions: {}

jobs:
  echo-inputs:
    name: "Echo Inputs"
    runs-on: ubuntu-latest
    steps:
      - id: echo
        name: "Echo Inputs"
        run: |
          echo "verbose=${{ inputs.verbose }}"
  about:
    name: "About"
    uses: "./.github/workflows/about.yml"
  main:
    name: "Main"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - about
    env:
      name: ${{ needs.about.outputs.name }}
      nodeVersion: ${{ needs.about.outputs.nodeVersion }}
      pnpmVersion: ${{ needs.about.outputs.pnpmVersion }}
      version: ${{ needs.about.outputs.version }}
    outputs:
      artifact-id: ${{ steps.upload-eslint-result.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-eslint-result.outputs.artifact-url }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: git-pull
        name: "Pull Changes"
        run: |
          git pull
      - id: installPnpm
        name: "Install: Use PNPM ${{ env.pnpmVersion }}"
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpmVersion }}
          run_install: false
      - id: installNodeJs
        name: "Install: Use Node.js ${{ env.nodeVersion }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: "pnpm"
      - id: install
        name: Install
        run: |
          pnpm install --frozen-lockfile
      - id: lint
        name: "Lint"
        run: |
          pnpm --recursive lint --output-file eslint.out.txt
      - id: upload-eslint-result
        name: "Upload ESLint Result"
        uses: actions/upload-artifact@v4
        with:
          name: eslint-out
          path: eslint.out.txt
          retention-days: 30
  verbose:
    name: "Verbose"
    runs-on: ubuntu-latest
    needs:
      - main
    if: ${{ inputs.verbose }}
    steps:
      - id: output
        name: "Output"
        run: |
          echo "# ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* ESLint Results: [${{ needs.main.outputs.artifact-id }}.zip](${{ needs.main.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY
