name: "Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type.'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: true
      dryRun:
        description: "If to perform a dryRun without push at the end."
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      release_type:
        description: 'Release type.'
        required: true
        default: 'patch'
        type: string
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: false
      dryRun:
        description: "If to perform a dryRun without push at the end."
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "Released version"
        value: ${{ jobs.release.outputs.version }}
      nextVersion:
        description: "Snapshot version"
        value: ${{ jobs.snapshot.outputs.version }}

run-name: |
  ${{ github.workflow }} (release type: ${{ inputs.release_type }}, dry-run: ${{ inputs.dryRun }}, verbose: ${{ inputs.verbose }})

env:
  # https://github.com/actions/runner-images/issues/70
  NODE_OPTIONS: "--max_old_space_size=4096"

permissions:
  contents: write

jobs:
  echo-inputs:
    name: "Echo Inputs"
    runs-on: ubuntu-latest
    steps:
      - id: echo
        name: "Echo Inputs"
        run: |
          echo "dryRun=${{ github.event.inputs.dryRun }}"
          echo "release_type=${{ github.event.inputs.release_type }}"
          echo "verbose=${{ github.event.inputs.verbose }}"
  release:
    name: "Release Version"
    uses: "./.github/workflows/release-version.yml"
    secrets: inherit
    with:
      dryRun: ${{ inputs.dryRun }}
      release_type: ${{ inputs.release_type }}
  build:
    name: "Build Release"
    uses: "./.github/workflows/build.yml"
    needs:
      - release
  snapshot:
    name: "Increase Snapshot Version"
    uses: "./.github/workflows/inc-snapshot-version.yml"
    needs:
      - build
    secrets: inherit
    with:
      dryRun: ${{ inputs.dryRun }}
  main:
    name: "Main"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build
      - release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - id: gh-release
        if: ${{ ! inputs.dryRun }}
        name: "Create Release"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ needs.build.outputs.artifact-name }}.zip
          tag_name: ${{ needs.release.outputs.version }}
      - id: gh-release-dry-run
        if: ${{ inputs.dryRun }}
        name: "Create Release (Dry Run)"
        run: |
          echo "Would create a release with ${{ needs.build.outputs.artifact-name }}.zip"
  verbose:
    name: "Verbose"
    runs-on: ubuntu-latest
    needs:
      - main
      - release
      - snapshot
    if: ${{ inputs.verbose }}
    steps:
      - id: output
        name: "Output"
        run: |
          echo "# Release Version" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Parameters" >> $GITHUB_STEP_SUMMARY
          echo "* Released Type: ${{ inputs.release_type }}" >> $GITHUB_STEP_SUMMARY
          echo "* Verbose: ${{ inputs.verbose }}" >> $GITHUB_STEP_SUMMARY
          echo "* Dry-Run: ${{ inputs.dryRun }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Released Version: ${{ needs.release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "* Snapshot Version: ${{ needs.snapshot.outputs.version }}" >> $GITHUB_STEP_SUMMARY
