name: "Release Version"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type.'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      release_type:
        description: 'Release type.'
        required: true
        default: 'patch'
        type: string
      verbose:
        description: "If to output a summary."
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "Released version"
        value: ${{ jobs.main.outputs.version }}
      nextVersion:
        description: "Snapshot version"
        value: ${{ jobs.main.outputs.nextVersion }}

env:
  # https://github.com/actions/runner-images/issues/70
  NODE_OPTIONS: "--max_old_space_size=4096"

permissions:
  contents: write

jobs:
  about:
    name: "About"
    uses: "./.github/workflows/about.yml"
  main:
    name: "Release Version"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - about
    env:
      nodeVersion: ${{ needs.about.outputs.nodeVersion }}
      pnpmVersion: ${{ needs.about.outputs.pnpmVersion }}
      userName: ${{ github.actor }}
      userMail: "${{ github.actor }}@users.noreply.github.com"
    outputs:
      version: ${{ steps.inc-version.outputs.result }}
      nextVersion: ${{ steps.inc-snapshot-version.outputs.result }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: installPnpm
        name: "Install: Use PNPM ${{ env.pnpmVersion }}"
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpmVersion }}
          run_install: false
      - id: installNodeJs
        name: "Install: Use Node.js ${{ env.nodeVersion }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: "pnpm"
      - id: install
        name: Install
        run: |
          pnpm install --frozen-lockfile
      - id: config
        name: "Config"
        run: |
          git config --global user.name "${{ env.userName }}"
          git config --global user.email "${{ env.userMail }}"
      - id: inc-version
        name: "Increment Version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          releaseType=${{ github.event.inputs.release_type }}
          releaseVersion="$(pnpm version --silent "${releaseType}" --message "chore: release ${releaseType}: %s")"
          echo "result=${releaseVersion}" >> $GITHUB_OUTPUT
      - id: inc-snapshot-version
        name: "Increment Snapshot Version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          snapshotType="prerelease"
          snapshotVersion="$(pnpm version --silent "${releaseType}" --no-git-tag-version)"
          git commit -am "chore: next snapshot version: ${snapshotVersion}"
          echo "result=${snapshotVersion}" >> $GITHUB_OUTPUT
      - id: git-push
        name: "Push Changes"
        run: |
          git push --follow-tags
  verbose:
    name: "Verbose"
    runs-on: ubuntu-latest
    needs: main
    if: ${{ github.event.inputs.verbose }}
    steps:
      - id: output
        name: "Output"
        run: |
          echo "# Release Version" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Released Version: ${{ needs.main.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "* Snapshot Version: ${{ needs.main.outputs.nextVersion }}" >> $GITHUB_STEP_SUMMARY
